ALTER TABLE events ADD COLUMN IF NOT EXISTS activity_id INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS kind_id INTEGER;
ALTER TABLE events ADD COLUMN IF NOT EXISTS manually_mapped BOOLEAN DEFAULT false;
